Jenkinsfile
This reverts commit ac9cba808447099e411c66615973b160a21fb936.
=> Revert "swotch to use the docker pipeline template"

config/webpack.common.js, config/webpack.dev.js
removes common chunks and copy plugin
=> fix(build): remove unnecessary code

src/app/kubernetes/components/resource-header/resource.header.component.scss, src/app/kubernetes/components/resource-header/resource.header.component.ts, src/app/kubernetes/ui/space/space.module.ts
also fix resource header css leaking into global scope
=> fix(modules): fix space module dependencies

src/index.html
=> fix(package): fix jquery errors

src/app/kubernetes/components/resource-header/resource.header.component.html
=> fix: make the button a button

README.md, config/webpack.dev.js, config/webpack.prod.js, config/webpack.test.js, package.json, src/app/app.component.ts, src/app/app.module.ts, src/app/header/header.component.ts, src/app/kubernetes/service/kubernetes.restangular.ts, src/app/shared/api-locator.service.ts, src/app/shared/auth-api.provider.ts, src/app/shared/login.service.ts, src/app/shared/sso-api.provider.ts, src/app/shared/wit-api.provider.ts
This requires ngx-login-client 0.6.4 to complete
Also - there is still a CORS issue accessing the sso api directly, will need @pmuir's assistance
=> feat(addauth): adds ngx-login integration

src/app/dummy/dummy.service.ts, src/app/kubernetes/store/kuberentesresource.store.ts, src/app/kubernetes/store/namespacedresource.store.ts, src/app/kubernetes/ui/buildconfig/list-page/list-page.buildconfig.component.ts
=> fix(buildconfigs): fix loading issue of new namespace resources

package.json, src/app/common/common.module.ts, src/app/kubernetes/components/components.module.ts, src/app/kubernetes/components/resource-header/resource.header.component.html
=> fix(resource-header): Added correct DropdownModule to common module

src/app/app.module.ts, src/app/approuting/approuting.module.ts, src/app/dummy/dummy.service.ts, src/app/header/header.component.ts, src/app/kubernetes/service/watcher.ts, src/app/kubernetes/store/kuberentesresource.store.ts, src/app/kubernetes/store/space.store.ts, src/app/shared/onlogin.service.ts, src/app/shared/token.resolver.ts
removes onlogin callback which is unnecessary in integrated environment
=> fix(token): add token resolver and remove onlogin

src/app/kubernetes/model/helpers.ts, src/app/kubernetes/model/kubernetesresource.model.ts, src/app/kubernetes/model/service.model.ts, src/app/kubernetes/ui/build/list/list.build.component.html, src/app/kubernetes/ui/buildconfig/list/list.buildconfig.component.html, src/app/kubernetes/ui/deployment/list/list.deployment.component.html, src/app/kubernetes/ui/pod/list/list.pod.component.ts, src/app/kubernetes/ui/service/list/list.service.component.html, src/app/kubernetes/view/deployment.view.ts
=> feat(links): add links to openshift console for most resources

src/app/app.module.ts, src/app/kubernetes/ui/environment/list-page/list-page.environment.component.ts, src/app/kubernetes/ui/environment/space-namespace.service.ts, src/app/kubernetes/ui/environment/space-namespace.ts
* Create a service with an interface to provide this so we can replace it easily
=> fix: extract space/label extraction

src/app/kubernetes/service/kubernetes.service.ts, src/app/kubernetes/service/namespaced.resource.service.ts
this also fixes the create label space in fabric8-ui
=> fix(create): fixes up the creation methods in the services

src/app/app.module.ts, src/app/kubernetes/ui/configmap/configmap.module.ts, src/app/kubernetes/ui/deployment/deployment-routing.module.ts, src/app/kubernetes/ui/environment/environment-routing.module.ts, src/app/kubernetes/ui/environment/list-page/list-page.environment.component.ts, src/app/kubernetes/ui/event/event.module.ts, src/app/kubernetes/ui/pod/pod.module.ts, src/app/kubernetes/ui/replicaset/replicaset.module.ts, src/app/kubernetes/ui/service/service.module.ts, src/app/shared/no-notifications.service.ts
* Error on null spaces
* Don't use lazy loading of children, it breaks on reuse in another project
=> fix: environments

src/app/kubernetes/ui/environment/list-page/list-page.environment.component.ts
Previously it displayed on load
=> fix: display the count on load

src/app/app.component.spec.ts
These tests on the app.component are simple enough, but they fail stating
that the Broadcaster needs a Provider. It is in the Provider, so they have
been commented out until which time this can be sorted out.
=> fix(tests): comment out failing tests

src/app/kubernetes/model/buildconfig.model.ts
fixes #152 by reusing the same array for BuildConfig.interestingBuilds to avoid needless flicker. Thanks for the heads up @dgutride
also fixed a few gremlins not correctly showing the latest interesting build (or running builds in general if not the latest)
=> fix(flashing): fixes flashing

src/app/kubernetes/model/build.model.ts, src/app/kubernetes/model/buildconfig.model.ts, src/app/kubernetes/model/pipelinestage.model.ts, src/app/kubernetes/ui/pipeline/build-stage-view/build-stage-view.component.html, src/app/kubernetes/ui/pipeline/full-history/full-history.pipeline.component.html, src/app/kubernetes/ui/pipeline/history/history.pipeline.component.html, src/app/kubernetes/ui/pipeline/list/list.pipeline.component.html
lets add service links to the pipelines UI so folks can open services in
each environment via the stages or kebab menu
=> feat(pipelines): add service links

src/app/kubernetes/components/pipeline-status/pipeline-status.component.scss
lets avoid any animation on anything other than in progress stages to avoid most of the flickering
=> feat(pipelines): fix flashing

src/app/kubernetes/components/pipeline-status/pipeline-status.component.scss
the previous fix to remove flashing left some rendering issues; finally figured out how to avoid the unecessary corners on the ticks and crosses over the circles
=> fix(pipelines): tidy css

config/webpack.dev.js, config/webpack.prod.js, config/webpack.test.js, src/app/kubernetes/model/build.model.ts, src/app/kubernetes/model/kubernetesresource.model.ts, src/app/kubernetes/model/pipelinestage.model.ts, src/app/kubernetes/ui/pipeline/build-stage-view/build-stage-view.component.html, src/app/kubernetes/ui/pipeline/build-stage-view/build-stage-view.component.ts, src/app/kubernetes/ui/pipeline/full-history-page/full-history-page.pipeline.spec.ts, src/app/kubernetes/ui/pipeline/full-history/full-history.pipeline.spec.ts, src/app/kubernetes/ui/pipeline/history-page/history-page.pipeline.spec.ts, src/app/kubernetes/ui/pipeline/history/history.pipeline.spec.ts, src/app/kubernetes/ui/pipeline/input-action-dialog/input-action-dialog.component.html, src/app/kubernetes/ui/pipeline/input-action-dialog/input-action-dialog.component.scss, src/app/kubernetes/ui/pipeline/input-action-dialog/input-action-dialog.component.ts, src/app/kubernetes/ui/pipeline/list-page/list-page.pipeline.spec.ts, src/app/kubernetes/ui/pipeline/list/list.pipeline.spec.ts, src/app/kubernetes/ui/pipeline/pipeline.module.ts, src/app/shared/onlogin.service.ts
lets add a dialog so that we can Proceed or Abort directly from the console
using the Forge API to communicate with jenkins to avoid CORS issues
=> feat(pipelines): add input dialog

src/app/kubernetes/model/build.model.ts, src/app/kubernetes/model/buildconfig.model.ts, src/app/kubernetes/ui/pipeline/list/list.pipeline.component.html
so that we can easily link to the summy of unit/integration tests on a pipeline
=> feat(test-reports): lets add a link to the test reports for a build

src/app/kubernetes/model/build.model.ts, src/app/kubernetes/ui/pipeline/build-stage-view/build-stage-view.component.html
Changes:
1. build.model.ts - Added repositoryInformation variable to get the repository information from the pipeline (This is needed for the Bayesian component tht is present inside the build stage)
2. build-stage-view.component.html - Changed the Bayesian module include structure to accomodate the new include.
=> fix(repo_info): change the build model to accomdate the repository information

src/app/kubernetes/ui/pipeline/input-action-dialog/input-action-dialog.component.html, src/app/kubernetes/ui/pipeline/input-action-dialog/input-action-dialog.component.scss
applied Catherine's latest UX for the promote dialog
=> fix(approve): updated UX

src/app/kubernetes/model/build.model.ts, src/app/kubernetes/model/buildconfig.model.ts
lets add a function to return all the environments and for each environment return the name and all the apps, their version and deployUrl so we can easily view summaries per environment or per app
=> feat(apps-function): add an appsInfo function

index.ts, src/app/kubernetes/model/build.model.ts, src/app/kubernetes/model/helpers.ts, src/app/kubernetes/model/kubernetesresource.model.ts, src/app/kubernetes/model/scalableresource.model.ts, src/app/kubernetes/model/service.model.ts, src/app/kubernetes/model/space.model.ts, src/app/kubernetes/support/abstract-watch.component.ts, src/app/kubernetes/ui/app/app-routing.module.ts, src/app/kubernetes/ui/app/app.module.ts, src/app/kubernetes/ui/app/list-page/list-page.app.component.html, src/app/kubernetes/ui/app/list-page/list-page.app.component.ts, src/app/kubernetes/ui/app/list-page/list-page.app.spec.ts, src/app/kubernetes/ui/app/list-toolbar/list-toolbar.app.component.html, src/app/kubernetes/ui/app/list-toolbar/list-toolbar.app.component.scss, src/app/kubernetes/ui/app/list-toolbar/list-toolbar.app.component.ts, src/app/kubernetes/ui/app/list-toolbar/list-toolbar.app.spec.ts, src/app/kubernetes/ui/app/list/list.app.component.html, src/app/kubernetes/ui/app/list/list.app.component.scss, src/app/kubernetes/ui/app/list/list.app.component.ts, src/app/kubernetes/ui/app/list/list.app.spec.ts, src/app/kubernetes/ui/deployment/deployment.module.ts, src/app/kubernetes/ui/deployment/list/list.deployment.component.ts, src/app/kubernetes/ui/deployment/scale-dialog/scale-dialog.deployment.component.html, src/app/kubernetes/ui/deployment/scale-dialog/scale-dialog.deployment.component.ts, src/app/kubernetes/ui/deployment/view/view.deployment.component.ts, src/app/kubernetes/ui/environment/list-page/list-page.environment.component.ts, src/app/kubernetes/ui/space/delete-dialog/delete-dialog.space.component.ts, src/app/kubernetes/ui/ui.module.ts, src/app/kubernetes/view/deployment.view.ts
this new page shows a summary of all the apps in each environment, the version, numnber of pods and their states and the links to test out the apps in a single, simple view that folks can use to keep an eye on things #454
=> feat(apps page): adds a new apps page

src/app/kubernetes/model/buildconfig.model.ts, src/app/kubernetes/ui/app/list-toolbar/list-toolbar.app.component.scss, src/app/kubernetes/ui/pipeline/list/list.pipeline.component.html, src/app/kubernetes/ui/pipeline/list/list.pipeline.component.scss
lets avoid an excessive top margin on the pipelines page
=> style(pipelines): polish

src/app/kubernetes/service/namespaced.resource.service.ts, src/app/kubernetes/ui/buildconfig/delete-dialog/delete-dialog.buildconfig.component.html, src/app/kubernetes/ui/buildconfig/delete-dialog/delete-dialog.buildconfig.component.ts, src/app/kubernetes/ui/pipeline/list/list.pipeline.component.html
deleting of buildconfig/pipelines was broken; fixed it up to avoid JSON.stringify issues
=> fix(pipelines): fix deletion

src/app/kubernetes/service/namespaced.resource.service.ts, src/app/kubernetes/ui/app/list-page/list-page.app.component.ts, src/app/kubernetes/ui/deployment/delete-dialog/delete-dialog.deployment.component.ts, src/app/kubernetes/ui/deployment/scale-dialog/scale-dialog.deployment.component.ts, src/app/kubernetes/ui/replicaset/delete-dialog/delete-dialog.replicaset.component.ts, src/app/kubernetes/ui/replicaset/scale-dialog/scale-dialog.replicaset.component.ts
lets filter the apps on the space labels
=> fix(space): filter on space

src/app/kubernetes/ui/pipeline/history-toolbar/history-toolbar.pipeline.component.html, src/app/kubernetes/ui/status/status-info.component.html, src/app/kubernetes/ui/status/status-list.component.html, src/app/kubernetes/ui/status/status-list.component.ts
lets make the UI look nicer when its used dynamically
=> fix(statuslist): make status list lazy

src/app/kubernetes/model/helpers.ts, src/app/kubernetes/service/kubernetes.restangular.ts, src/app/kubernetes/store/oauth-config-store.ts, src/app/kubernetes/ui/pipeline/build-stage-view/build-stage-view.component.html, src/app/kubernetes/ui/pipeline/list/list.pipeline.component.html, src/config/oauth.json
lets allow configuration of the proxy API server host for running on premise
=> fix(envvars): add proxy api server host

src/app/kubernetes/service/build.service.ts, src/app/kubernetes/service/buildconfig.service.ts, src/app/kubernetes/store/apis.store.ts
lets detect an environment variable to indicate kubernetes rather than openshift style REST APIs
=> fix(kubernetes): discover kubernetes mode

src/app/kubernetes/service/watcher.ts, src/app/kubernetes/store/oauth-config-store.ts, src/config/oauth.json
lets allow websockets to be proxied at the a path relative to the current web app
=> fix(websocket): lets allow websocket proxying

src/app/kubernetes/service/watcher.ts, src/app/kubernetes/store/oauth-config-store.ts, src/config/oauth.json
lets make it easier to default to ws:// when using http:// for API access
such as if using the nginx proxy when hosted on http:// versus https://
=> chore(kubernetes): easier config

src/app/kubernetes/ui/status/status-info.component.html, src/app/kubernetes/ui/status/status-list.component.html, src/app/kubernetes/ui/status/status-list.component.scss, src/app/kubernetes/ui/status/status-list.component.ts
Update the status widget with the new designs. Static content added until APIs are connected.
closes https://github.com/fabric8-ui/fabric8-ux/issues/522
=> fix(status): update status widget with new designs

src/app/kubernetes/kubernetes.store.module.ts, src/app/kubernetes/service/kubernetes.service.ts, src/app/kubernetes/service/namespaced.resource.service.ts, src/app/kubernetes/service/openshift.namespaced.resource.service.ts, src/app/kubernetes/service/poller-factory.service.ts, src/app/kubernetes/service/poller.ts, src/app/kubernetes/service/resource-operation.ts, src/app/kubernetes/service/watcher-factory.service.ts, src/app/kubernetes/service/watcher.ts, src/app/kubernetes/store/kuberentesresource.store.ts, src/app/kubernetes/store/space.store.ts, src/app/kubernetes/support/abstract-watch.component.ts, src/app/kubernetes/view/deployment.view.ts
if the websocket API is not enabled via CORS then lets fallback to polling
instead
=> feat(polling): support polling if no websockets

src/app/kubernetes/store/kuberentesresource.store.ts
fixes https://github.com/fabric8-ui/fabric8-ui/issues/1707
=> fix(duplicates): avoid duplicates on pipeline UI

environments/devshift-cluster.sh, environments/integration-cluster.sh, environments/local-cluster.sh, environments/openshift-free-int-cluster.sh, environments/openshift-prod-cluster.sh, src/app/app.module.ts, src/app/shared/realm.provider.ts
Since this commit https://github.com/fabric8-ui/ngx-login-client/commit/52f4143bbc2032017eecbddf30b428042a6da2b7 we now need to provide realm.
=> fix(realm): realm provider is needed by ngx-login dependency
